### ISSUE TITLE
Loss of subclass information

### ISSUE THREAD

**Issue by joshmoore** [linkml/linkml#1008]
I'm attempting to use `linkml-convert -f ttl` to produce a more hierarchical format that can be used to, e.g., build a website. I'm finding, however, that the type information that I need for each of the hierarchies in my model are being stripped out.

In rdflib_loader.py:

```
                     if o not in processed:
                         # if o instantiates a class, add to list of nodes to be visited.
                         # force type based on range constraint
                         if slot.range in schemaview.all_classes():
                            node_tuples_to_visit.append((o, ClassDefinitionName(slot.range)))
 ```
this code is used to create the `dict_obj` instances which get passed on to generators. The use of `slot.range` effectively drops information about which subclass was found, e.g. based on the `class_uri` information.

Is this by design?

In attempting to build a generator that needs this information, I found that I could maintain the subclass information by replacing the above with:

```
+                            class_def = ClassDefinitionName(slot.range)
+                            for possible_type in graph.objects(o, RDF.type):
+                                possible_class = uri_to_class_map.get(str(possible_type))
+                                if possible_class:
+                                    logging.debug(f"Replace class_def: {class_def} with {possible_class.name}")
+                                    class_def = ClassDefinitionName(possible_class.name)
+                                    break
+                            node_tuples_to_visit.append((o, class_def))
```

Passing that information to a generator, however, is still an issue since adding new fields to the `dict_obj` fails later during `{base_type_name}(**as_dict(obj)`. (I have a local workaround which detects a new `@type` field and strips it out again, e.g.:

```
+++ b/linkml/generators/pythongen.py
@@ -164,6 +164,16 @@ dataclasses._init_fn = dataclasses_init_fn_with_kwargs
 # Namespaces
 {self.gen_namespaces()}

+# Helper
+def _instantiate(v, base_type):
+    if isinstance(v, base_type):
+        return v
+    else:
+        obj = as_dict(v)
+        if "@type" in obj:
+            type_name = obj.pop('@type')
+            base_type = globals()[type_name]
+        return base_type(**obj)

 # Types
 {self.gen_typedefs()}
@@ -812,7 +822,7 @@ dataclasses._init_fn = dataclasses_init_fn_with_kwargs
                     )
                 else:
                     rlines.append(
-                        f"\tself.{aliased_slot_name} = {base_type_name}(**as_dict(self.{aliased_slot_name}))"
+                        f"\tself.{aliased_slot_name} = _instantiate(self.{aliased_slot_name}, {base_type_name})"
```

but I do wonder if I've missed something simple that would allow me to keep this information.

**Comment by cmungall** [comment]
[moved to the main linkml repo as it's easier to track]

Good sleuthing!

Minor comment:
> this code is used to create the dict_obj instances which get passed on to generators

In our terminology (which may not be the best), a generator is a general class of things that generate things from a *schema*. In the rdflib_loader, the dict_obj is used to initialize an instantiated dataclass (which itself was made by a generator)

i.e. this line: `return [target_class(**x) for x in root_dicts]`

In any case, you have hit the nail on the thread. there isn't a lot of point in adding more granular information, as this gets lost when constructing an object from json/yaml/a dictionary anyway.

As you note, the enhancement to rdflib_loader has to be accompanied by a change in the generated dataclasses, to make use of some kind of type designator.

And your proposed solution is exactly along the lines of what we plan here:

- #945

The idea is to be a little bit more general and allow you to define your own field that acts as a type designator, rather than using the jsonld `@type` fields.

It may be possible to implement something more flexible, such that if no type designator is provided, we fall back to `@type`, and pythongen (and pydanticgen) can make use of either. We could potentially progress with your solution, then implement #945 later. We'd have to proceed carefully here as we want to make sure that older versions of the runtime are still compatible.

**Comment by cmungall** [comment]
Covered by #945
