### ISSUE TITLE
Auto-release to dockerhub with each release

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1102]

**Comment by capsulecorplab** [comment]
Dropping documentation link here https://docs.docker.com/docker-hub/builds/link-source/

**Comment by pkalita-lbl** [comment]
@cmungall I think I have a pretty good handle on how to do this. There are two general approaches:

1. Connect this repo to Docker Hub and let it handle the build and push. The documentation for that is what @capsulecorplab (thank you!) linked. 
2. Add a new workflow in the GitHub Actions for this repo; use the [actions that Docker provides](https://docs.docker.com/build/ci/github-actions/) to coordinate the build and push.

I think I'd lean towards the GitHub Actions option since we have other workflows for things like publishing to PyPI. It might be nice to have everything in one place, so to speak.

If you want to go forward with the GitHub Actions, you (or another admin on this repo) need to generate a Docker Hub access token and [add it as a secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) (probably called something like `DOCKER_HUB_ACCESS_TOKEN`) to this repo. Once that's in place I can put together a new workflow.

**Comment by cmungall** [comment]
Thanks both!

@pkalita-lbl I have set DOCKER_HUB_ACCESS_TOKEN

**Comment by cpauvert** [comment]
:+1: for auto-release! Thanks! As a side note, the current image [`linkml/linkml`](https://hub.docker.com/r/linkml/linkml/tags) is built only for linux/arm64 architecture. Is there a plan in the auto-release to also include amd64 for instance?

**Comment by pkalita-lbl** [comment]
@cpauvert Yes the plan is to automatically do multi-arch builds for each release

**Comment by cpauvert** [comment]
> @cpauvert Yes the plan is to automatically do multi-arch builds for each release

Good news! For now, the following command : `docker run -v $(pwd):/work -w /work/ --rm -ti linkml/linkml` fails with 

```bash
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
exec /bin/bash: exec format error
```

**Comment by pkalita-lbl** [comment]
A Docker image for the latest LinkML release has been pushed to Docker Hub under the tags `1.3.14` and `latest`. There is also an image tagged as `main` that has the bleeding edge development version of LinkML; that's probably not of great interest to most people but it's there. Going forward each new release of LinkML should automatically result in a new semver tag (`x.y.z`) and update the `latest` tag on Docker Hub. @cpauvert @capsulecorplab please let us know if you run into any trouble with these new images.

**Comment by cpauvert** [comment]
thanks @pkalita-lbl, the image works on my architecture amd64!

**Comment by capsulecorplab** [comment]
Thanks! @pkalita-lbl ! I just ran the image against the validators and converters for the examples in [Part 1: Creating your first LinkML schema](https://linkml.io/linkml/intro/tutorial01.html) on my laptop running Ubuntu 20.04, so it's probably safe to say the image seems to be working for typical use cases on my end as well.

Though, the example usage in https://hub.docker.com/r/linkml/linkml seems a bit misleading, as the `linkml-ws --help` example works, but `linkml-ws` doesn't actually generate a project scaffold, s.a. with `linkml-ws new my-linkml-project`. I opened an issue for this in #1117, which was closed because there's a cookiecutter template, but unless the `linkml-ws` feature itself is being deprecated, I'm of the opinion that the issue isn't actually resolved.
