### ISSUE TITLE
`type` in json dump should be `@type`

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#116]
The JSON serializer emits a `type` variable in the outermost element.  We need to consider:

a) Changing this to `@type` so we don't have any potential collisions w/ LinkML variables
b) Emit it in ALL classes, not just the outermost

Note that one drawback of taking this approach is that it will _force_ `rdf:type` arcs to be emitted on all subjects.  I would propose that we add the ability to produce arcs as an option.  Possibilities could include "none", "top" or "all" (default: "all").

**Comment by nlharris** [comment]
Is this still relevant?

**Comment by turbomam** [comment]
> Is this still relevant?

I don't know whether it is still relevant for @TomConlin or @hsolbrig but I am interested in this because the nmdc-schema has a local `type` slot, with range `string`. Values in that slot seem to block the emission of `rdf:type` statements in the RDF data artifacts, so I would like to deprecate that and rely more on more structured solutions, like @hsolbrig suggested in the initial post.
