### ISSUE TITLE
Should poetry.lock files be included in the libraries?

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1194]
When we were using `pipenv`, we didn't include the `pipenv.lock` files in the library (e.g. linkml-runtime, linkml-model, ...) distros
because doing so would make things nearly impossible to integrate.

I'm not familiar enough with poetry to know whether poetry.lock files serve a similar function but, if they do, we may want to consider adding it to the `.gitignore` file.  

Also note that two seemingly compatible changes to `poetry.toml`  -- changing version on one import and adding another, resulted in a rather icky merge error on poetry.lock.

**Comment by capsulecorplab** [comment]
@hsolbrig curious, what were the issues encountered with incorporating a `pipenv.lock`? The purpose of a lockfile is supposed to serve as an optional means of reproducing a working build.

**Comment by hrshdhgd** [comment]
@hsolbrig the `pyproject.toml` file states which minimum version of packages are used as dependencies for the project. The `poetry.lock` file anchors it down to the exact version and is the source of truth for all versions of all dependencies that have been tested and verified to work with each other. 

The reason of keeping the lock file in version control is when users use the tool, they have the exact version of dependencies installed that work together without complaints. If say we don't version control the lock file, when a user runs `poetry install`, it will create a new `poetry.lock` file locally with all versions for all packages that are latest at that point of time and may introduce incompatibility errors. Debugging errors that we've never seen before (since our versions don't match) adds more time and head scratching to figure out.

By providing the `poetry.lock` file, all of us are using the same version and eliminates an extra layer of debugging to figure out which package is the source of the error and which version is compatible.

**Comment by hsolbrig** [comment]
Again, while not intimately familiar with the poetry lock files, the problem we faced with the `pipenv` equivalent was:

    Library MyTools requires `rdflib="~6.2.0" -- any version of 6.2 is fine. 
    Library YourTools also requires `rdflib="~6.2.0" 
    My App requires the latest version of MyTools and YourTools

MyTools gets published with rdflib 6.2.1
YourTools gets published with rdflib 6.2.2

*IF* MyTools and YourTools include the `pipenv.lock` files, you will NOT be able to load MyApp because of version incompatibilities.

The solution we settled on in the `pipenv` situation would be that libraries would exclude lock files and end-user apps would include them.  We never fully decided what to do in the case of projects that could be _both_ libraries and end-user apps, but had tended towards excluding the lock files as well.

**Comment by cmungall** [comment]
@hsolbrig in the above scenario, MyApp is presumably installing MyTools and YourTools from PyPI, so the contents of the `poetry.lock` in both MyTools and YourTools is irrelevant.

See the tar or wheels here for example: https://pypi.org/project/linkml/#files -- they are pinned according to the pyproject.toml

Now it may be the case that you are doing something clever with submodules, and I am not 100% sure exactly what the behavior might be here

**Comment by pkalita-lbl** [comment]
I'd echo Chris's statement and also point to the Poetry documentation which is pretty clear that committing the lock file does not have any impact on downstream clients of your library: https://python-poetry.org/docs/libraries/#lock-file

**Comment by hsolbrig** [comment]
Appreciate the clarification.  As I said, I was not familiar w/ poetry, so I was assuming the same behavior as pipenv.  What had caused me to file this issue was a project where I'd added linkml and linkml-runtime as submodules and poetry had whined.  It must have been due to the "0.0.0" version identifiers instead of the lock files.
