### ISSUE TITLE
Loaders and Dumpers need command line interface

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#126]
The various loaders and dumpers (yaml_, json_, rdf_) need a command line option.

**Comment by hrshdhgd** [comment]
I do not see the `loaders` and `dumpers` folders in the project. They were present a few iterations ago since my local version has it.  From a [test file](https://github.com/linkml/linkml/blob/main/tests/utils/loaderdumpertestcase.py#L9) imports, I see they have been shifted to [`linkml-runtime`](https://github.com/linkml/linkml-runtime/tree/main/linkml_runtime). Am I missing something?

**Comment by cmungall** [comment]
You are correct, they are in linkml-runtime, but we are using this repo for issues to avoid issues being confusingly strewn across the org

**Comment by cmungall** [comment]
but you should follow the patterns for the CLIs in this repo

**Comment by cmungall** [comment]
Fixed in #304
