### ISSUE TITLE
converting from JSONLD

### ISSUE THREAD

**Issue by satra** [linkml/linkml#1278]
we have a bunch of schemas in jsonld (example: https://github.com/ReproNim/reproschema/tree/master/terms). i know i can go from linkml to jsonld, is there a way to go the other way around? or from turtle to linkml ?

**Comment by cmungall** [comment]
https://github.com/linkml/schema-automator can be used to bootstrap a linkml schema from an external framework. However, the tools here should be treated as more heuristic and less stable than the core linkml framework.

For your question in particular, JSONLD is not a schema language, so it doesn't quite make sense to translate general jsonld in the wild to linkml (although a certain amount of schema information can be scraped from jsonld *contexts*).

You can use schemauto to *generalize* from instance data in JSON or JSONLD/RDF, but that's not what you want here I think.

However, when I look at the link you provided, this looks like an RDFS schema that happens to be serialized as JSONLD. Or more specifically, the schema.org extension of RDFS. For this task you want to use the [OWL importer](https://linkml.io/schema-automator/packages/importers.html#importing-from-owl). Some general caveats:

- Every RDFS/OWL ontology makes use of different properties. Some use plain rdfs vocabularies (label, comments). Others use SKOS. Others use dcterms. Some use schema.org. Some use OBO/OIO/OMO. Many are a mix. Currently the importer hardcodes some assumptions, but in future it will be more configurable
    - Luckily, the OWL importer *is* aware of the schema.org extensions you are using (schema:domainIncludes, schema:rangeIncludes), so these are translated to the appropriate LinkML constructs.
    - Unfortunately the default mappings are suboptimal for you. E..g you use rdfs:comment to denote what would be a description in linkml, but rdfs:comment is mapped to comments in linkml
- The OWL importer needs OWL functional syntax as input.
    - Fortunately piecing together different W3C specs tell us how to get from JSONLD to functional syntax
    - Unfortunately this is not straightforward in practice. ROBOT will convert *most* semantic formats to OFN, but you may need to use something like jena or rdflib to get from your jsonld to something robot considers acceptable input
    - It looks like you are already making ttl files available, but only for some products? I filed an issue here https://github.com/ReproNim/reproschema/issues/450
- Modular schemas are great but there are specific challenges in bringing in a modular schema
    - it looks like you are not making your dependency structure explicit e.g. using owl:imports, so if I convert `reproschema.ttl` I will end up with range violations, e.g. references to Activity which is defined in a separate module
    - we recently added something to the jsonschema importer that will infer a module structure based on references and directory layout, but no such thing exists for the OWL importer yet


I notice you also have SHACL - does this include additional constraint information not in the RDFS? If so that may be a good target (there is no SHACL importer in schemauto but this wouldn't be hard to add).

And not to complicate further, but it looks like your schema has basis in the CEDAR data model - we work closely with members of the CEDAR team are interested in broader interoperation use cases here.

**Comment by satra** [comment]
thanks @cmungall - we don't need a perfect converter, but something that can help the process. our test would be to see if we can generate a JSONLD document that matches the original one (subject to any mistakes we may have made).

re: cedar and reproschema:

there are unfortunately many chains of history here. our original work indeed started with cedar, but then diverged once we got to the point of generating the actual data for these reproschema models (those sit in the reproschema-library). i think the main thing was that the data models diverged because we were in a place where we wanted to use this to collect data (reproschema-ui was built to do that), and we needed to make faster/sometimes broken changes to get that going. hence it was more an engineering effort rather than data modeling. with data modeling happening as we needed to describe more elements, including mixing information about an element and how that element could be presented (i.e. ui).

this presentation provides a little bit of that background: https://docs.google.com/presentation/d/1H4C_cBU9BE9EYFNyK8YBLQObzvq9iDztLWrqRIQTmgc/edit#slide=id.p

happy to see if there is a convergence that happens.

**Comment by cmungall** [comment]
Ah, it looks like properties like `about` are uncommitted to OWL types. https://github.com/linkml/schema-automator/issues/114

**Comment by cmungall** [comment]
It turns out that trying to force everything through OWL is not a great solution (e.g. many rdfs schemas in the wild lack commitment as to OWL property types).

We added RdfsImporter, which accepts RDFS natively, is more configurable than the OWL one, and also accepts schema.org domain/range extensions.

next schemauto release you can do this:

```
poetry run schemauto import-rdfs tests/resources/reproschema.ttl -n reproschema -o ~/tmp/reproschema.yaml
```

results attached

[reproschema.yaml.txt](https://github.com/linkml/linkml/files/10575029/reproschema.yaml.txt)

there are still issues, particularly the dangling references like Number, etc (schemauto will infer some dangling types but it won't go off to the web to introspect schema.org types). Also a class Number is not a very linkml-like way of modeling..

**Comment by satra** [comment]
thanks @cmungall - we can work with this. on the schema.org front, have you considered/created a linkml version of schema.org ?

@sooyounga , @djarecja - let's chat about this sometimes soon.

**Comment by sierra-moxon** [comment]
@satra - I believe there are some folks working on a LinkML version of bioschemas (but not far enough along to post yet :)). 

Do you have enough information here to close this ticket?
