### ISSUE TITLE
add documentation about defaults

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#135]
If possible, I think it would be good to add a section in the documentation regarding default configurations.

E.g.:
- For schema validation, are slots required by default?
- When a slot is multivalued, is it inlined or not inlined by default?
- An explanation of how mixins are used in linkml would be great too.
- Explanations of slot_usage and attribute when defining classes.

**Comment by sierra-moxon** [comment]
I think this was added before the tutorials and documents were put in place.  I imagine we can still do more to document best practices, especially around inlining, but we do have the linter as well.  I'm going to close this for now; please reopen if there are specific conventions that are broken or otherwise still confusing.  :)
