### ISSUE TITLE
the range for `minimum_`... and `maximum_value` should be something more flexible than integer... at least float!

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1384]
Why can't the minimum `height_meters` for riding a roller coaster be 0.8 ?

**Comment by sujaypatil96** [comment]
The range for `maximum_value` and `minimum_value` slots is `Integer`:
* https://linkml.io/linkml-model/docs/maximum_value/#properties
* https://linkml.io/linkml-model/docs/minimum_value/#properties

**Comment by turbomam** [comment]
Yes, I am proposing that we change it to float.

**Comment by pkalita-lbl** [comment]
Beyond numeric types it would be useful to be able to apply `minimum_value` and `maximum_value` to date/dateTime slots as well. It was discussed here:

* https://github.com/linkml/linkml/issues/751
* https://github.com/linkml/linkml-model/issues/53

But I think those conversations lost the plot when they started talking about a special `{today}` value. As it stands if I just want to express "a date from 1997" I want to just say:

```yaml
slots:
  the_date:
    range: date
    minimum_value: 1997-01-01
    maximum_value: 1997-12-31
```

But that doesn't adhere to the metamodel.

**Comment by ddooley** [comment]
If we could just translate dates/datetime values to unix time integer, then we could also test minimum_value etc against that too (as integers).  So coerce date/time into integer?

**Comment by cmungall** [comment]
I’d recommend holding tight for now if you can…

**Comment by sneakers-the-rat** [comment]
+1 to this, any way I can help out making it happen?

**Comment by cmungall** [comment]
Thanks!

First let's enumerate all the types we want to allow: numbers (integer,
float, decimal), date, datetime, time. Any more?

There is an argument for strings or characters, but this would be confusing
and I think most use cases here could be solved with `pattern`

We should also decide which combinations of data value type and constraint
value type are permissible. I think this is:

- numeric x numeric is always permitted. This includes `maximum_value: 4.2`
when the slot range is integer (rationale: constraints may be specified for
a grouping classes where the range is any number, and subclasses may
restrict ranges to integers)
- {date, time, datetime} x {date, time, datetime} - [ time x date, date x
time ] is permitted?
- no other combinations are permitted, i.e the following are errors
    - specifying a time min/max constraint for a date slot
    - specifying any min/max constraint on a string, curie, uri, slot
    - no implicit time conversions, to unix times or any other such scheme

I believe this is more permissible than json-schema, which only has max/min
for numbers?

While deciding this we can start the PR on linkml-model

1. relax the range of the metaslot to `Anything`
2. additionally, include an exactly_one_of enumerating each of the allowed
ranges

This would be slated for 1.7.0.

**Comment by sneakers-the-rat** [comment]
I wonder if there is any room for hierarchical/derived types in linkml? eg. similar to how Python's duck typing works, we could have a meta-type for "ordinal" that is a mixin for any type that can have greater than/less than relations. I see this already existing with some mixins like [Extensible](https://linkml.io/linkml-model/latest/docs/Extensible/), or could that be an `implements: Ordinal` thing?

Agreed re: strings not being ordinal and re: errors on incompatible inequalities. 

I think what lets us be more expressive than JSON-Schema is having an actual type system, which we can make use of :).

Another comparison is xsd, eg see [minExclusive, maxExclusive, et al](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#maxInclusive-maxExclusive). That relies on a [value space](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dt-value-space) of a datatype, including [order/ordinality](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#order).

So yes i think that rather than having it be ad-hoc or some property that only some `enum` of base types can have, we can make an `Ordinal` mixin/implements/etc. whatever you think would fit that types can inherit from, so then the definition is easier: `minimum_value` and `maximum_value` can be used on any `Ordinal` type, and any future type that implements `Ordinal` needs to provide some method for evaluating order. We can punt on what that looks like until there's a more formal 'plugin' system for declaring types that might need to come with code to do that evaluation.

**Comment by cmungall** [comment]
Great suggestion. We can also look to cuelang for underlying formalism.

We may still wish to progress *as if* there were an explicit Ordinal type or metatype, I think that would be valid, and would allow us to move on this a little faster.

**Comment by sneakers-the-rat** [comment]
Up to you! Im not sure how hard that would be to make the metaclass / whether it would be more work to do it twice, so happy to follow your lead there. Lmk how I can help :)

**Comment by cmungall** [comment]
Schedule for 1.7 series

**Comment by cmungall** [comment]
Added a test for this: #2145
