### ISSUE TITLE
LinkML validation: Allow extra fields not included in schema 

### ISSUE THREAD

**Issue by Shalsh23** [linkml/linkml#1404]
**Is your feature request related to a problem? Please describe.**

We are trying to use the validation tool to validate data files being uploaded to ESS-DIVE portal and ensure that they adhere to a specific schema specified using linkml. Although we would like to specify the constraints on a set of fields and their values, we do not want to stop people from including additional fields in the data file. The current validation tool, however, throws an error when it encounters additional fields. For example, `[ValidationMessage(severity=<SeverityEnum.error: 'Error'>, field=None, value=None, message="Additional properties are not allowed ('Header_Rows', 'Location_ID' were unexpected)")]`

**Describe the solution you'd like**

We would like to be able to successfully validate data files which adhere to a specific schema even if they have additional fields that are not included in the schema.

**How important is this feature?** 

Important - We cannot release our validation tool to ESS-DIVE users without this feature.

**When will use cases depending on this become relevant?** 

Short term - 1 month

**Additional context**

We did [find a parameter](https://github.com/linkml/linkml/blob/6ca5d7e1e65f2fc956053465d06e1da0b080fd9b/linkml/validators/jsonschemavalidator.py#L69) `closed` in `JsonSchemaValidator.validate_dict()` which allows us to achieve this functionality. But it would be useful to have access to this parameter directly in the command line validation tools. Also, there isn’t much documentation for this parameter except for [this](https://linkml.io/linkml/generators/json-schema.html#cmdoption-gen-json-schema-not-closed), which is difficult to understand and not directly relevant to our use case.

**Comment by turbomam** [comment]
Thanks for the excellent LinkML data validation issues, @Shalsh23, It's one of my favorite topics.

Just regarding this extra fields/open schema issue:
- you aren't the first person who has asked open-schema validation. It's a controversial request because there are strong arguments for and against open schemas.
- do you make a distinction in your schema between required, recommended and optional slots?
- can you share a link to your schema's repository?
- have you anticipated the disadvantages of an open schema?
  - Consider users feeling like they must put some of their values in un-specified fields because they don't have enough familiarity with the provided fields. In the worst case scenario, they will only fill in the required fields and use their own out-of-schema fields for every other value. When multiple users do this, it leads to less interoperability between the data sets. 
  - People providing open schemas should plan for an **increased burden** of training users, maintaining the schema and migrating data from out-of-schema slots into schema-defined slots. Even if re-align-able fields are found in different users' submissions, it may be difficult to align the values or types: string, number, enumerations, etc.

There are multiple ways of validating data against LinkML schemas and improving the simplicity and functionality of the validators is an active topic of discussion.

Can you provide something that shows specifically what validation strategy you're using? A Makefile would be great if you have one. I can have a zoom meting with you if you want.

**Comment by pkalita-lbl** [comment]
This is partially addressed in the validation refactor (#1494). That will allow passing a `closed` parameter to the `JsonSchemaValidationPlugin`, but it will only affect how _root-level_ extra fields are handled. FIne-tuning closed-vs-openness down through all levels of a nested object structure is a much more tricky thing to handle and will require https://github.com/linkml/linkml/issues/1595 as a prerequisite.

**Comment by sneakers-the-rat** [comment]
closed by: https://github.com/linkml/linkml-model/pull/205
