### ISSUE TITLE
What should we expect from data validation re. simplicity and coverage?

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1434]
I am a very appreciative user of LinkML data validation tools, especially from the command line.

I think we should make it as **easy** and **well-documented** as possible to do **thorough** validation programmatically or with the CLI. I believe that will require a combination of Python instantiation-based validation (e.g. no duplicated identifiers for instances of class X in a collection) and JSON Schema validation (e.g. for regular expressions).

From the CLI, current tools include (but may not be limited to)
- linkml-validate
- linkml-run-examples

Data can also be validated in code or with tools from third parties (some commodity software and some offerings from people who are already closely aligned with LinkML). There also also tools that embed validation, like linkml-convert.

There are already several good issues in this repo tagged with [linkml-validate](https://github.com/linkml/linkml/issues?q=is%3Aissue+is%3Aopen+validation+label%3Alinkml-validate)

Validation is mentioned int he documentation in a few places, like 
- https://linkml.io/linkml/data/validating-data.html
- https://linkml.io/linkml/intro/tutorial03.html

**Comment by bede** [comment]
Hi, @turbomam mentioned this issue, having suggested [the following function](https://github.com/pha4ge/primaschema/blob/f85aeac8abb2c564ca9dd7d58df682ce74e0a91a/src/primaschema/lib.py#L213) to me as a LinkML newbie, and so I thought I'd comment.

I found the `linkml-validate` and `linkml-convert` CLI scripts really intuitive as a new user. However, as I was implementing some Python tooling I assumed it would be possible to mimic this functionality using Python APIs, and it was a little more complicated than anticipated. It seems that the recommended route is to use Pythongen and then import its output, but IMO the UX for newbies would be improved dramatically if this could be distilled to a single high-level function call equivalent to `jsonschema.validate()`. I guess this would take objects as args rather than paths like my version.

```python
def validate_with_linkml_schema(yaml_path: Path, schema_path: Path):
    schema_view = SchemaView(schema_path)
    schema_gen = PythonGenerator(schema_view.schema)
    schema_compiled = schema_gen.compile_module()
    data = parse_yaml(yaml_path)
    data_instance = schema_compiled.PrimerScheme(**data)
    validator = JsonSchemaDataValidator(schema_view.schema)
    validator.validate_object(data_instance)
```

**Comment by cmungall** [comment]
I think this is more straightforward now with the new validator framework: #1494

**Comment by cmungall** [comment]
Can we close this?

**Comment by bede** [comment]
Thanks – fine by me – just getting my head around the new framework
