### ISSUE TITLE
Consider dropping support for Python 3.7

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1519]
Some LinkML packages (at least `linkml-runtime` and `linkml`) support [some Python 3.7 versions](https://github.com/linkml/linkml/blob/fa359e617889291dc7c6ed26e6e823a42f298c29/pyproject.toml#L99). As of 2023-06-27, [Python 3.7 is in end-of-life status](https://devguide.python.org/versions/). We should probably consider raising our minimum Python version to 3.8. We can reasonably expect that [packages we depend on](https://github.com/cthoyt/curies/pull/59) will drop support for 3.7 soon and we don't want to be forced to use old versions of those packages.

Also it looks like Python releases are now going to be added and deprecated in October of each year for the foreseeable future. We should keep that in mind as a good time to update our own minimum version, tested versions, etc.

**Comment by dalito** [comment]
On the other end: 3.11 support could be added to CI. Note, that 3.7 was already removed from CI.

**Comment by cmungall** [comment]
I am OK with this. Should we do this in the next minor version series, since raising the minimum version could break dependency resolution?

**Comment by pkalita-lbl** [comment]
Makes sense to me. 

I also agree this would be a good opportunity to take a look at our testing version matrix and make sure we're happy with it.

**Comment by dalito** [comment]
Since you need to keep many repositories at the same state in terms of CI, I wonder if the [approach suggested by jaracho](https://blog.jaraco.com/skeleton/) could help to keep them all in line. You would need a template directory where you update shared files and then apply git to pull/merge the changes into the others. In my experience this works well and I prefer this to cookiecutter/cruft. Might be worth a try.
