### ISSUE TITLE
Duplicate in identifier field not failing in online linkml-tutorial. 

### ISSUE THREAD

**Issue by amc-corey-cox** [linkml/linkml#1571]
**Describe the bug**
Duplicate in identifier field not failing in online linkml-tutorial. 

**To reproduce**
1. Go to https://linkml.io/linkml/intro/tutorial03.html
2. Follow tutorial instructions to create `personinfo.yaml` and `better-data-v1.yaml`
3. Validate the data with:
```
linkml-validate -s personinfo.yaml bad-data.yaml
```
4. We should receive the following error but instead the data validates:
```
ValueError: File "<file>", line 6, col 9: ORCID:1234: duplicate key
```

**Expected behavior**
The expected error should occur when the id's are duplicate

**About your computer (if applicable, please complete the following information):**
 - OS: Ubuntu 22.04 with bash

**Additional context**
I'm uncertain whether this is a bug in linkml or the online tutorial or if this isOS specific to Ubuntu. I copied and pasted the data from the website directly so it shouldn't be a typo or such. I'm happy to test/troubleshoot.

**Comment by amc-corey-cox** [comment]
This may be a duplicate of:
https://github.com/linkml/linkml/issues/1542

**Comment by pkalita-lbl** [comment]
A long time ago the `linkml-validate` would deserialize your data file into a LinkML-generated `@dataclass` object, then convert that object into a plain Python `dict`. That `dict` was then used as part of a JSON Schema-based validation workflow.

The `@dataclass` step introduced a lot of undesirable side-effects and so at some point it was removed. But one of those side-effects (which was actually sort of desirable) was failing on duplicate keys. I guess the documentation didn't get updated to reflect that at the time.

Later still we introduced an entirely new validation framework in [the `linkml.validator` package](https://linkml.io/linkml/data/validating-data.html#the-linkml-validator-package-and-cli). With those changes I _did_ remember to update the documentation and removed the bit about failing on duplicate keys. 

Since the current documentation and functionality are in-sync I'm closing this issue. 

Having the validator flag duplicate keys is a good idea and I think we can use #1542 for that.
