### ISSUE TITLE
Tutorial part 1: data.yaml does not validate

### ISSUE THREAD

**Issue by heikkil** [linkml/linkml#1612]
**Describe the bug**

Tutorial part 1 schema file personinfo.yaml declares all attributes to be strings. 
However, the example data file data.yaml contains a line:
age: 32
that is recognised as a number.

This kind of error at the very beginning of the tutorial can be very discouraging to newbies.

**To reproduce**

$ cd linkml/examples/tutorial/tutorial01/ 
$ linkml-validate -s personinfo.yaml data.yaml
✗ 32 is not of type 'string' in $.age

This would be easy to fix by adding single quotes around the integer, but the other alternative would be to change the schema. 
Also, the age in the file data.json is a number.

 - OS: MacOS 13.4. 
 - python version: 3.11.5

**Comment by cmungall** [comment]
hi @heikkil, good to see you here!

Yes, the default behavior use to be to coerce some types where possible, but this ended up being more confusing than helpful. I fixed the example so that in part 1 age is explicitly a string, then we switch to using integers in part 2 onwards. On reflection it may have been better to use a different example in part 1 but for now I opted to modify the flow as little as possible.

**Comment by heikkil** [comment]
Hi @mungall and @sierra-moxon,

I really appreciate this and SSSOM work. Truly useful hands-on instructions in this area are hard to find. 

I did not do a pull request as there were too many options available to solve it, and they all have knock on effects. I'll try to improve in the future.

Best, 
 H
