### ISSUE TITLE
linkml-runtime 1.6.1 causes too-strict curie validation to break common biomedical CURIE syntax

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#1701]
**Describe the bug**
"CURIEs" like `WIKIDATA_PROPERTY:P854` and `WIKIDATA.PROPERTY:P854` register as  `is not a valid URI or CURIE` errors with linkml-runtime 1.6.1

**To reproduce**
see test changes (and commented out code) in https://github.com/linkml/linkml-runtime/pull/283

**Expected behavior**
For better or worse, these are "valid" curies and should not generate error states by default.   It could be that we need to specify "strict=False".

**Comment by sierra-moxon** [comment]
@Silvanoc - any ideas here?

**Comment by Silvanoc** [comment]
The issue is not that the CURIE validation is too strict. The issue is that it's wrong! Sorry, my fault combined with poor test coverage for valid CURIEs. I'll create a PR for this, I'll first push tests to reproduce the issue to be fixed (avoiding the regression in the future) and the fix the issue.
