### ISSUE TITLE
Release v1.6.2 of linkml-runtime is missing in pypi.org

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1711]
**Describe the bug**
linkml-runtime v1.6.2 has been already [released](https://github.com/linkml/linkml-runtime/releases/tag/v1.6.2) by now for 5 days, but it's stil missing in pypi.org

**To reproduce**
Visit the [linkml-runtime page in pypi.org](https://pypi.org/project/linkml-runtime/) and confirm that version 1.6.2 of linkml-runtime is missing.

Alternatively run `pip index versions linkml-runtime` and confirm that version 1.6.2 doesn't show up there.

**Expected behavior**
linkml-runtime v1.6.2 can be installed using PIP.

**Comment by Silvanoc** [comment]
There must be something wrong with the [pypi publication CI job](https://github.com/linkml/linkml-runtime/blob/main/.github/workflows/pypi-publish.yaml). #1713 is probably related to this issue.

**Comment by pkalita-lbl** [comment]
For some reason the PyPI publish workflow chose to [checkout a commit hash](https://github.com/linkml/linkml-runtime/actions/runs/6802878871/job/18496946303#step:3:466) instead of a tag for the release. Later, when it went to set the version based on the tag name, [it failed because there was tag to reference](https://github.com/linkml/linkml-runtime/actions/runs/6802878871/job/18496946303#step:7:9). With the version still set at `0.0.0`, the actual publish step failed because that version already exists. 

I've manually published the 1.6.2 release, so I'm going to close this issue. We haven't changed anything about the PyPI publish workflow in a while so I'm willing to chalk it up to a one-time fluke and keep a close eye on the next release.
