### ISSUE TITLE
Proposal: Deprecation timeline for pydantic v1?

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#1925]
Maintaining two versions of the pydantic generator is decent amount of work for increasingly diminishing returns. Pydantic 2 is here to stay (and is really good!). It was released in [june 2023](https://docs.pydantic.dev/2.0/blog/pydantic-v2-final/), and it seems like a ~year-ish of migration time is plenty. So, since this project does rolling releases and it doesn't make sense to target a specific version for deprecation, shall we pick a date for dropping support for pydantic v1?

- [ ] Pick a date for deprecation - Loose suggestion would be 6 months after we add the deprecation warning
- [ ] Add a deprecation warning - When pydanticgen is used with pydantic v1, alert the user that they will need to update their downstream project to use pydantic v2!
- [ ] Survey affected projects - I am not sure what projects are out there that still depend on pydantic v1, it would be nice to have at least an incomplete list, for documentation if not to help triage migration work todo

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

supporting v1 and v2 doubles a lot of work on pydanticgen!

**When will use cases depending on this become relevant?** Select from the options below:

Edit: this is now short term for me, without dropping pydantic 1 i'm going to work on a fork until we do

**Comment by sneakers-the-rat** [comment]
Is there any compelling reason aside from being kind to give adaptation time for keeping pydantic 1? it's strictly deprecated at this point, 100% of the functionality is ported over to 2, anyone who is already using pydantic 1 models should be able to switch to pydantic 2 without any loss of function (from linkML at least, their downstream derivatives may be affected). cost of maintenance is pretty dang high and will only get higher

**Comment by cmungall** [comment]
It's not always easy for everyone to migrate to pyd2 - all it takes is one recalcitrant direct or indirect dependency. Python really needs proper vendoring/shading, see [my comments on python.org](https://discuss.python.org/t/can-vendoring-dependencies-in-a-build-be-officially-supported/13622/11).

However, we don't need to support new features in pydanticgen for `1` as a target. If arrays are only allowed in `2` this is acceptable since we are not depriving anyone of functionality they once had. I realize this doesn't completely alleviate the complexity of supporting both.

I propose:

1. feature freeze on `pydantic_version=1` as a target in pydanticgen effective immediately
2. drop `pydantic_version=1` as a target in pydanticgen in linkml 1.8.0
3. force `pydantic^2` in pyproject.toml in linkml-runtime in 1.9.x or 1.10.x series

We have projected May for 1.8.0 but this could be brought forward https://github.com/linkml/linkml/milestones

**Comment by sneakers-the-rat** [comment]
that works for me!!! I can PR deprecation warnings and docs later today. Do we have a system for deprecations already? and if not I can make a page in the docs for deprecation timelines.
