### ISSUE TITLE
Generate PlantUML locally or mark all tests flaky

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#1956]
**Describe the bug**
PlantUML generation depends on a web API called "kroki": https://github.com/linkml/linkml/blob/0c3afa90701dd18ce874f6103cc7668684eb697d/linkml/generators/plantumlgen.py#L97-L105

however this is not a reliable way to generate plantUML, as it intermittently fails during test runs, which still take ~20-30m to do, eg. https://github.com/linkml/linkml/actions/runs/8153290936/job/22284373873?pr=1887

If there is any package that can generate plantUML locally, we should use it, otherwise we should mark any test that the plantUML class touches as [flaky](https://docs.pytest.org/en/stable/explanation/flaky.html)

**Comment by dalito** [comment]
plantuml (the java package) would be required in CI to generate images. It can be done, but checking the generated "puml" code should be sufficient for linkML in my opinion. For sphinx I prefer to use the puml-file and to generate the svg image as part of the docs build.

So maybe image generation from puml via an external service should not be part of linkML´s plantuml support?

**Comment by Silvanoc** [comment]
> So maybe image generation from puml via an external service should not be part of linkML´s plantuml support?

I would do something intermediate:

1. As proposed by @dalito, generate by default only PlantUML code and test the code generation.
2. Additionally make the already existing argument `--kroki-server` act simultaneously as a flag: if passed with a value, generate the SVG of the diagram using the provided Kroki server. Then test only the correctness of the generated Kroki API request without even interacting with a real server.
 
That way the generator doesn't have a real external dependency to be tested and all flakiness will disappear.

**Comment by sneakers-the-rat** [comment]
oh ya 1) should definitely be done for all the generators, good unit tests in addition to the end to end generation tests. 
I'll PR 2) in a second - imo that's just polite in addition to the perf benefits and test robustness, and should generally apply to any tests that make network requests. we can use https://pytest-vcr.readthedocs.io/en/latest/

**Comment by sneakers-the-rat** [comment]
for recordkeeping: the tests that still make network requests atm are - 

- test_base/test_metamodel::test_meta_markdown - 86 requests
- ''::test_meta_rdf - 15 requests
- test_generators/test_plantuml::test_generate_svg - 1 request
- test_generators/test_rdfgen:;test_annotation_extensions - 6 requests
- test_issues (all from 1-6 requests)
  - 112
  - 12
  - 163
  - 3
  - 381
  - 163
  - 384
  - 388
- test_scripts/test_gen_markdown::test_issue_2 - 2 requests
- test_scripts/test_gen_rdf::test_metamodel - 18 requests
- ''::test_make_script - 6
- test_scripts/test_gen_shex::test_meta - 2 requests
- test_scripts/test_gen_yuml::test_metamodel_output_directory - 4 requests
- ''::test_formats - 12 requests
- ''::test_specified_diagram_name - 2 requests
- test_utils/test_schemaloader::test_importmap - 4 requests

**Comment by sneakers-the-rat** [comment]
ok i fought with this all day, and i tried two things - to use the existing requests_cache package and monkeypatch urllib to use that cache, which worked, except then i kept getting cache misses because that package just isn't designed for this kind of thing.

then i went to using pytest-recording, which worked, except for that `hbreader` package which is just not very well written, bc for a package that is designed to be 'read anything, no questions asked' it makes a lot of assumptions about the form of the input for no discernable reason. it wants to use urllib to open a url as if it were a file object, which is just like ??? behavior to me.

anyway that's here, about as much as i'll do on this bc i patched my local version and i really only care about this bc it's annoying to have to wait for network requests when running tests: https://github.com/linkml/linkml/compare/main...sneakers-the-rat:linkml:tests-vcr-all?expand=1

**Comment by VladimirAlexiev** [comment]
LinkML can:
- Use plantuml.jar locally
- Use https://www.plantuml.com/plantuml/ online
- Build and use https://github.com/plantuml/plantuml-server as a self-hosted server

I asked why use kroki.io and @Silvanoc said
> I use Kroki in order to support self-hosted diagram generators. That is in fact what we use in our company.

Does LinkML use through Kroki any other tools listed at https://kroki.io/#support, eg Mermaid?
- If so then it makes sense to use Kroki and not the PlantUML server.
- If not then it's better to use the PlantUML server because it's always up to date.

Kroki:
![](https://kroki.io/plantuml/svg/eNpzKC5JLCopzc3hKkstKs7Mz-NySM1LAfIBfZAJnA==)

PlantUML:
![](https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuIfBBIhEpC_ZSaZDIm7n0G00)

@Silvanoc
> If I'm right, the APIs are slightly different and I didn't want to add support for both.

You are right. The above two diagrams use the same code, but if you compare the URLs, the encoding schemes are different.
```
@startuml
version
@enduml
```

**Comment by Silvanoc** [comment]
@VladimirAlexiev I personally don't have anything against adding support for the PlantUML server directly.

But I would disagree with the removal of the support for Kroki, since I get in my company a centrally-hosted Kroki instance, but no PlantUML. That's why I contributed support for Kroki and not the PlantUML server. I think that adding also support for the PlantUML server shouldn't be difficult. The URL are not that complex to generate.

**Comment by sierra-moxon** [comment]
kroki strikes again: https://github.com/linkml/linkml/actions/runs/8809179191/job/24179574590?pr=2079

**Comment by vincentkelleher** [comment]
Hi @sneakers-the-rat and all 👋 

I've been distressed by Kroki test failures as I had to modify a file in my pull request, commit and force push to rerun validation tests...

A [solution I've implemented recently](https://github.com/linkml/linkml/pull/2318/commits/5173871364823a283d7c258009af999584e8aaf1) was to run a Kroki server container via [TestContainers](https://testcontainers.com/) (which I've used for years for integration testing) and point the tests towards that server instead of kroki.io. This solution works flawlessly on Linux based machines but not on Windows based machines as the Kroki Docker image doesn't support their architecture, so I had to disable the use of the container for those.

I would suggest that we either :

1. make a custom build of the Kroki server Docker image to support the Windows architectures
2. disable Windows validation tests which must exist for a reason
3. host our own Kroki server, it can be done in minutes but I don't want to make the project depend on a server that I host myself so I could only help in setting up that server to avoid ownership 😇
