### ISSUE TITLE
Best practice to publish pydantic model to pypi as a python package

### ISSUE THREAD

**Issue by manulera** [linkml/linkml#1970]
I want to use the pydantic models generated by LinkML in another project. Ideally I would publish the pydantic classes as a python package, and add the package as a dependency for the other project. 

I was wondering if there is some best practices on how to do this. If not, I am happy to share the solution I end up with, and document it in the linkml docs if you think it's good.

**Comment by sneakers-the-rat** [comment]
only thing i would add is that you probably want to distribute the schema along with them, and keep the generated models as their own (unmodified) module. and then what I would do personally is expose them as a public API through a different module in case you want to make modifications to them later.

So eg., something like this at first:

`_models.py`
```python
class MyModel(ConfiguredBaseModel):
    # the fields...
    
class MyModel2(ConfiguredBaseModel):
    # more fields...
```

`models.py`
```python
from ._models import *
```

and then in the future if you want to make modifications to the models you could do something like
`models.py`
```python
from ._models import MyModel, MyModel2 as _MyModel2

class MyModel2(_MyModel2):
    def new_method(self):
        # some new method you want on the model
```

so that way you can both regenerate the models at will when you change the schema, but also have any sort of custom behavior you want, without having to do some breaking change to the API later - rather than exposing the models directly, you have a layer of abstraction to work with.

**Comment by manulera** [comment]
Thanks for the recommendations @sneakers-the-rat . I had thought of something like that for custom methods or to customise some properties if linkml is not flexible enough, so I guess I am on the right track!

**Comment by manulera** [comment]
Hello all, thanks for the help! I managed to publish based on that github action and makefile. Here is a link to the GH action that I ended up using, in case someone comes back in the future. It uses a "trusted publisher" instead of token/password for pypi.

https://github.com/genestorian/ShareYourCloning_LinkML/blob/master/.github/workflows/pypi-publish.yaml

Cheers,
Manu
