### ISSUE TITLE
Autodetect pydantic version in gen-pydantic 

### ISSUE THREAD

**Issue by manulera** [linkml/linkml#2077]
**Is your feature request related to a problem? Please describe.**
Now, the `gen-pydantic` cli tool does not autodetect pydantic version. It defaults to one unless you specify `--pydantic-version`

**Describe the solution you'd like**
It would be nice if it auto-detected it, since it took me a second to understand why it was not working (some of the code auto-detects the version)

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term - 6 months - 1 year

**Additional context**
Will provide a short PR with fix

**Comment by sneakers-the-rat** [comment]
pydanticgen actually does use the pydantic version in the environment by default: https://github.com/linkml/linkml/blob/bd989b3a8d7fd336532a35a4019fca8877e915d6/linkml/generators/pydanticgen/pydanticgen.py#L133

it's just the CLI that defaults to 1: https://github.com/linkml/linkml/blob/bd989b3a8d7fd336532a35a4019fca8877e915d6/linkml/generators/pydanticgen/pydanticgen.py#L726

but yeah pydantic 1 generation is marked for deprecation: https://linkml.io/linkml/code/deprecation.html#pydanticgen-v1

I could go either way on this one:

pro single default: because there is a distinction between the version of pydantic that is in the environment and the version of models that you're generating - in the same way that we might want to generate models for different versions of the JSON-LD spec, but not have that be dependent on the version of rdflib, I think that should in general be an explicit choice, and that also makes things more consistent across generators. I also agree with @cmungall here that if you are doing periodic model generation it would be surprising to suddenly have your generated models change because eg. some dependency has updated their pydantic constraint. 

pro detect environment: the reason why i switched the generator to detecting the pydantic version was the expectation that when people are using the generator programmatically, they probably want to be consuming and using those models immediately. especially now that linkml defaults to pydantic 2, when someone has pydantic 1 installed in their environment, they have already done that explicitly, they have already done so explicitly.

The change would be a single line, but we would want to do deprecation warnings and all that, so this fix would take maybe a week or two to roll out, and then only survive for a few months, so i would sorta lean slightly towards wontfixing autodetecting by environment.

> (some of the code auto-detects the version)

this on the other hand would be a bug if some of the parts of the generator autodetect and others don't - as written it should be the case that whatever is specified in the generator on instantiation should be the the one that's use throughout the generation process - all the template models take `self.pydantic_version`, they only autodetect when no value is explicitly provided, and there is one version detection in the generated models that changes what is imported depending on the version of pydantic that's installed (but that's just to simplify generation, it doesn't make the models compatible with both versions).

**Comment by kevinschaper** [comment]
I lean towards the root problem being that it's surprising at this point to have pydantic v1 as the default, and maybe it would be worth swapping to auto only if it comes up again after v2 is the default?  It seems like a circumstance where you really want to detect for the CLI can be accomplished via shell wizardry right now or wrapping the pydanticgen code in your own python, but that this issue wouldn't have come up if we had already switched to defaulting to v2, so likely won't come up after?

**Comment by cmungall** [comment]
agree with @kevinschaper
