### ISSUE TITLE
Need testers for version 0.1.1.dev2

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#208]
We may update the dev version, but we need people to do `pip install 'linkml>=0.1.1.dev1'` and take it through its paces. It still has issues, but we don't want to be any _worse_ than linkml==0.0.7.  We are planning to make this into linkml 0.1.0 the week of May 24th unless someone says "no".

**Comment by cmungall** [comment]
Just to be clear, we want people to do this from their various model repos

**Comment by cmungall** [comment]
Works for KGCL (both generating artefacts, and the runtime)

**Comment by gaurav** [comment]
I'm running into an error in a project that includes both `linkml` (">=0.1.1.dev1") and `linkml_model` ("==0.0.10") -- it looks like `linkml_model` is trying to import `Slot` from `linkml.utils.slot`, but can't find that package:

```
  ...
  File "/Users/gaurav/Development/cancerDHC/ccdhmodel/generators/google-sheets/sheet2linkml/model.py", line 2, in <module>
    from linkml_model.meta import SchemaDefinition
  File "/Users/gaurav/.local/share/virtualenvs/google-sheets-See-rrZ0/lib/python3.9/site-packages/linkml_model/__init__.py", line 1, in <module>
    from linkml_model.types import String , Integer , Boolean , Float , Double , Decimal , Time , Date , Datetime , Uriorcurie , Uri , \
  File "/Users/gaurav/.local/share/virtualenvs/google-sheets-See-rrZ0/lib/python3.9/site-packages/linkml_model/types.py", line 15, in <module>
    from linkml.utils.slot import Slot
ModuleNotFoundError: No module named 'linkml.utils.slot'
```

I'm guessing this is just because `linkml_model` will be updated after the new `linkml` has been published, so this probably shouldn't hold up this release, but I thought I'd mention it.

**Comment by hsolbrig** [comment]
Try removing the linkml_model requirement completely

**Comment by cmungall** [comment]
I have run into this issue @gaurav I can help later

**Comment by gaurav** [comment]
Thanks, Chris and Harold! Removing `linkml-model` didn't work, since I need it to access the LinkML metamodel Python DataClasses -- unless there's a way of accessing them from the main `linkml` package that I don't know about? However, I was able to install "linkml-model==0.1.1.dev1", "linkml==0.1.1.dev2" and "linkml-runtime==1.0.5" and got back access to all the packages I need. So, I think publishing the new linkml-model fixed this!

I still have an odd error in the YAML generation process (`yaml.representer.RepresenterError: ('cannot represent an object', JsonObj(linkml='https://w3id.org/linkml/', ccdh='https://example.org/ccdh/'))`), but I'll wait until linkml and linkml-model are fully released before I file that as an issue against linkml-runtime. That way, I can make sure that this is in fact a bug in linkml-runtime and not just in my code somewhere :)

**Comment by smrgeoinfo** [comment]
I tried the 0.1.1 dev1, still doesn't generate enums (#201) or decimal data types (#202); result is same as 0.0.7.  Testing with https://github.com/isamplesorg/metadata/blob/main/iSamplesSchemaBasic.yml

**Comment by cmungall** [comment]
closing this as we are on 1.0.0. We will deal with @smrgeoinfo's infos in these other tickets
