### ISSUE TITLE
LinkML validator should provide a way to verify that entity references are correct

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#2116]
**Is your feature request related to a problem? Please describe.**

`MONDO:0008720|MONDO:0016042` is not a valid URI or CURIE. Entity references are a very fundamental concept in our world and should be validated by our validation system.

The original dataclasses pre-pydantic warned us:

```
WARNING:sssom.parsers:One mapping in the mapping set is not well-formed, and therfore not included in the mapping set ({'subject_id': 'NANDO:2200355', 'subject_label': 'Isolated ACTH deficiency', 'predicate_id': 'skos:exactMatch', 'object_id': 'MONDO:0008720|MONDO:0016042', 'mapping_justification': 'semapv:MappingCuration'}). Error: MONDO:0008720|MONDO:0016042 is not a valid URI or CURIE
````

The new LinkML validation system does not warn us about this malformed curie!

**Describe the solution you'd like**

Some way to validate entity references (curies / Uris) properly.

**How important is this feature?** Select from the options below:

• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:

• Short-term - 2-4 weeks

cc @pkalita-lbl 

See also https://github.com/mapping-commons/sssom-py/pull/532/files#r1604435772

**Comment by cmungall** [comment]
We can have the jsonschema generator create regexes. However, I am not sure this will help your specific scenario. You're assuming `|` is not a valid character to use, which I don't think is the case

the online jsonld playground handles this fine:

```json
{
  "@context": {
    "@base": "https://example.org",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ex": "https://example.org/"
  },
  "@id": "ex:123|ex:234",
  "@type": "Foo",
  "rdfs:label": "foo"
}
```

Jena tells us its "unwise"

```
riot --strict t.jsonld
17:48:07 WARN  riot            :: Bad IRI: <https://example.org/123|ex:234> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs. These characters are permitted in RDF URI References, XML system identifiers, and XML Schema anyURIs.
17:48:07 WARN  riot            :: Bad IRI: <https://example.org/123|ex:234> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs. These characters are permitted in RDF URI References, XML system identifiers, and XML Schema anyURIs.
<https://example.org/123|ex:234> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org/Foo> .
<https://example.org/123|ex:234> <http://www.w3.org/2000/01/rdf-schema#label> "foo" .
```

Complicating the picture further, LinkML CURIEs, like the curies in the `curies` package implements something looser than the specs, so we want an additional strict curie type, see:

- #258
- https://github.com/biopragmatics/curies/issues/103

**Comment by matentzn** [comment]
Hmmmmm, this does indeed complicate things. So how do you feel about this - on what level of the stack do we attack the `|`? If it is a valid, but "unwise", character, it seems wrong to add this to the default validators. 

What is the role of `|` in the LinkML stack? Is it used as a "built-in" to rollup inline lists of things, for example in CSV type formats? In this case the LinkML validator framework should spit out a warning at least. Another option would be to solve this issue on format specific levels (we could, as you say, put this in the regexes explicitly at schema-level, not LinkML-level, and then just let the validator that checks regexes deal with it). Not sure what is best!

**Comment by cmungall** [comment]
The "|" character has zero role in the core LinkML stack and specs. We are
forced to care about it in the csv loader/dumper, because CSV "standards"
are so dire. I think this is a more localized discussion that isn't about
validators per se: https://github.com/orgs/linkml/discussions/1996.

It's definitely wrong to be stricter than specs in core LinkML, but there
is nothing to stop you having a more restricted CURIE profile in a
particular data model, implemented via `pattern`. You may be reluctant to
do this in SSSOM as you don't know ahead of time that nobody has used "|"
in their IDs. If they have, then you need to mandate escaping of these
because you are already using | as an internal separator.

I think the best way to think about this is to think of CSV to
Dict/JSON/pandas/parquet as a local problem (due to aforementioned lack of
global CSV/TSV standards) and validating the structure as a LinkML one.

One thing that might help here is a "federated referential integrity"
plugin that can do lookups on IDs, but this is a hard task due to database
access heterogeneity (but see the OAK validate commands for examples of how
this might work). This would catch ID typos as well as programmatic errors
resulting in malformed IDs.

**Comment by matentzn** [comment]
This makes sense. I think for now, just because this is such a frequent issue, I will just treat this as a local issue in SSSOM, and not worry about generalising it to the validators. Your linked https://github.com/orgs/linkml/discussions/1996 is IMO the right place to have this discussion.

As I opened the issue, I will close it again, and the future person stumbling on this issue, should add their proposals here:

https://github.com/orgs/linkml/discussions/1996
