### ISSUE TITLE
slots in OWL output have unexpected IRIs and are not declared as properties

### ISSUE THREAD

**Issue by balhoff** [linkml/linkml#384]
I'm investigating some problems with the generated OWL for the CCDH model: https://github.com/cancerDHC/ccdhmodel/issues/64

I started by following the [linkml tutorial](https://linkml.io/linkml/intro/tutorial01.html#), and I think I see some of the issues in that simple example as well:

- Create `personinfo.yaml` as in https://github.com/linkml/linkml/blob/main/examples/tutorial/tutorial01/personinfo.yaml
- Run `gen-rdf personinfo.yaml >personinfo.ttl`. Observe the `phone` slot has IRI `<https://w3id.org/linkml/examples/personinfo/person__phone>`.
- Run `gen-owl personinfo.yaml >personinfo.owl.ttl`. Some problems:
  - The `phone` slot has IRI using the main `linkml` namespace: `<https://w3id.org/linkml/phone>`
  - The `phone` slot is not declared as any particular type of OWL property, e.g., `owl:ObjectProperty`
  - The `phone` slot is used in OWL restrictions without having been declared:
     ```
     <https://w3id.org/linkml/examples/personinfo/Person> a owl:Class,
        linkml:ClassDefinition ;
        rdfs:subClassOf [ a owl:Restriction ;
            owl:maxQualifiedCardinality 1 ;
            owl:onClass linkml:String ;
            owl:onProperty linkml:phone ]
     ```

All of this seems to be the cause of parsing failures found by the Java OWL API.

**Comment by cmungall** [comment]
First a comment on person__phone vs phone: generators differ in how they treat induced slots. See https://github.com/linkml/linkml/discussions/144

In general we don't have need of these in OWL as OWL is capable of expressing context-specific semantics for properties. The except is if you wanted to have a very general slot that had a type (literal) range in one class and a class range in another context - this would introduce punning. Ultimately we need to offer the schema author finer grained control over what the behavior of induced slots should be.

That aside, owlgen needs to be fixed so that it is using non-induced slot names universally. A quick workaround here is to declare the slots using a separate slots section: https://linkml.io/linkml/faq/modeling.html#when-should-i-use-attributes-vs-slots

(hmm, I thought the owlapi would infer the properties but I am never clear on it's rules... good to be explicit either way)

But this brings up another point with the OWL generation. It wants to model everything as OPs, and to treat types like 'string' as objects. I believe this is coherent, but it's not necessarily practical. I think we should allow a switch to have more direct modeling with DPs not OPs for types (literals).

**Comment by gaurav** [comment]
> First a comment on person__phone vs phone: generators differ in how they treat induced slots. See #144

Note that <https://w3id.org/linkml/examples/personinfo/person__phone> is a perfectly fine IRI for the "phone" property, especially since Protege will use the rdf:label of the property to identify this anyway, and I assume that will be set to "phone" or "Person.phone". The problem is that this property is referred to as `linkml:phone` (not `example:phone` or `example_personinfo:person__phone`) in the OWL logical expression. As we discussed on the LinkML call today, the solution for CCDH's needs for mangled slots will probably be be to use [`slot_uri`](https://linkml.io/linkml-model/docs/slot_uri/) to record what IRI each property should have, but I just wanted to clarify that I think you can fix all of Jim's other issues without changing the IRI at all (if I'm reading the issue correctly).

**Comment by cmungall** [comment]
correct, you can define your own slot_uris for these (I would recommend
just using a single underscore)
