### ISSUE TITLE
Multiple class_uri at same class

### ISSUE THREAD

**Issue by pabloalarconm** [linkml/linkml#471]
Hi, I'm struggling with the apparent limitation of not allowing multiple [class_uri parameter](https://linkml.io/linkml-model/docs/class_uri/) at one single [Class object](https://linkml.io/linkml-model/docs/ClassDefinition/) due to my intention define multiple rdf:type at same node.

There's any way to represent multiple rdf:type at same Class right now in your model language? If there's a way, could you show me how? Moreover, if you could show an example to me using YAML template representation, that would be great!

Thank you so much!
Pablo A

**Comment by cmungall** [comment]
Hi @pabloalarconm 

Interesting use case. So your intent is that serializing to RDF will create two rdf:type triples for instances of these classes?

How would it work in the reverse direction? Would it be necessary for both type triples to be present to map to the relevant object?

I think supporting this may be difficult as it violates some underlying assumptions, but I will let @hsolbrig answer definitively

However, if you expand on your use case more there may be other approaches that could help.

For example, you could have an explicit slot for types and take care of assigning these yourself. For example:

yaml:
```yaml
slots:
   types:
     slot_uri: rdf:type
     multivalued: true
     range: RDFSClass
...
```

you would then be responsible for setting these yourself:

```python
my_obj = MyClass(id=..., types=['sdo:C1', 'sdo:C2'])
...
rdflib_dumper.dump(my_obj, ...)
```


if this is on the right track for you, then we can help expanding the pseudocode above

**Comment by pabloalarconm** [comment]
Hi @cmungall Im glad to meet you, thank you for your response. My plan is to focus mostly on reverse direction right now. Im working on schema harmonization for my project's models [CDE semantic models](https://github.com/ejp-rd-vp/CDE-semantic-model/blob/develop/docs/personal_information.md) so, we have already our RDF data and im trying to represent this models with LinkML. As you can see, for example, Role node (Class) have multiple rdf:type already define it. Some of them are static (always the same rdf:type), but some of them (Sex patient information) could be represented as obo: NCIT_C16576 (Female) or obo: NCIT_C20197 (Male) and other possible validated instances shown in our ShEx below.

Due to these complexity of models, is range parameter able to define both these static and non-static rdf:types at LinkML YAML templates? Is these representation violates some underlying assumptions @hsolbrig? Is it feasible to represent these models as they are in current LinkML?

Thanks you so much,

@pabloalarconm

**Comment by gaurav** [comment]
@pabloalarconm Hi Pablo! Do you have an initial draft of the LinkML model that you're working on that I could take a look at? If I understand your problem correctly, I think Chris' proposed solution should work for you, and I'd be happy to try implementing it on your draft model. Once you have a multivalued `types` slot, we should be able to figure out some way to constrain it to a particular set of values.

**Comment by gaurav** [comment]
Hi @pabloalarconm! Just wanted to check in with you in the new year and see if this was still an issue for you. Otherwise, I can go ahead and close this issue now and you can reopen it again if you haven't found a workaround that works for you. Let us know!

**Comment by cmungall** [comment]
Hi @pabloalarconm 

What would the semantics of class_uri be for transformation?

For example:

```
  Person:
     class_uri: [foaf:Person, schema:Person]
```

given:

```turtle
:pablo a foaf:Person .
```

do we 

 - a. Treat the multi-URIs as a union, and allow this to be an instance of Person
 - b. treat as an intersection, and omit this

If we go with a, then note that roundtripping has the property of adding triples, since I assume we also want to emit both types for an instance of Person. This may not be disastrous, but I think preserving roundtripping is a good property.

one approach for you is to have two separate classes for each sense of the different class URIs. This would allow you to decide on a case by case basis whether it instantiates class_uriA, class_uriB, or both. But this is obviously awkward.

I think my preferred approach for your situation would be to treat this as being a case of an implicit inference step. For context, it's perfectly valid to add rdf:types for all superclasses and their equivalents to. And if you were to run your triples through [robot.reason](http://robot.obolibrary.org/reason) this is exactly what you would get. E.g.

```turtle
:my-role-001 a OBI:nnn, BFO:nnn, BFO:mmm, SIO:xxx, SIO:yyy
```

There is also a less well-defined reverse operation to eliminate redundancy - less well defined because in the case of equivalent pairs, it is arbitrary logically (but important sociotechnically) which you choose.

I *think* this is a good description of your situation. I am not sure of the initial provenance of your RDF and how you ended up with two class URIs. I don't think it's good to *manage* your triples this way due to violation of DRY (what happens if we later decide the OBI class and the SIO class are not equivalent? how many triples in how many triplestores do we need to change), but it can be a useful step to introduce redundant inferred information for query purposes.

So this gives you two paths:

First, you can do some preprocessing of the triples to remove redundancy and retain only the "preferred" URIs (and a reverse operation - which I conceive of as reasoning but you could simply see as adding the redundant triples). Formally there is no loss of information if we separately have equiv axioms between SIO and OBI. Then we are back to single class URIs. Preprocessing is sometimes inelegant and annoying but here I think it's quite a clean way to model what you have

The second path is to say 'I don't care about normalization / redundancy' and make the linkml model capture your structure as it is. In this case, I think we want to move rdf:type and the classes into the domain of discourse, and model them explicitly, following my guide further up. Now this is still a bit awkward, but we can pursue this further if this seems best for you.

**Comment by nlharris** [comment]
Can this be closed?

**Comment by pabloalarconm** [comment]
Yes, sorry for not giving some feedback sooner, we can close it, thank you so much for your contribution and comments.
