### ISSUE TITLE
degree of leafyness

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#489]
In the KG construction crew meeting, this morning, @justaddcoffee and @kevinschaper brought up that it would be nice to know the distance from the root class (or from a user-specified class) a class was in the class hierarchy.

We have methods to find all the leaf slots and leaf classes, maybe we could re-purpose the logic here in a wrapper method to put a distance on the classes in a hierarchy.  (linkml-runtime)

• Low - it's an enhancement but not crucial for work
• Short-term - 2-4 weeks

**Comment by cmungall** [comment]
would be easy to add but curious as to the use case, do we end up adding semantic similarity, etc

for some things like this it may be easier to translate to an ontology and use ontology graph metrics

**Comment by justaddcoffee** [comment]
I think the specific use case we were discussing was this - in Ensmallen, you only get one node type, but KGHub knowledge graphs often contain more than one. If you had to chose between typing a node as `biolink:NamedThing` or `biolink:Gene`, you'd choose the latter because it is more leafy and therefore more informative. 

So, to do this more generally in Ensmallen, we thought it would be good to read in the class hierarchy from the Biolink Model YAML, make it into a graph, and allow Ensmallen to choose the leafiest class for the node type.

**Comment by cmungall** [comment]
Rather than a heuristic/metric based approach, I think this is best served
by a deterministic subsumption based approach - enter a list of classes,
get back the non-redundant list.

Getting into biolink-specific rules: there SHOULD be exactly one
non-redundant type, once redundant classes are removed

I think that violations should generate a severe warning in KGX. KGX can
provide an option to supply a user-defined priority list to perform ad-hoc
repairs (but these should really be resolved upstream)

The one wrinkle here is where we deliberately allow conflation in clique
merging. E.g. gene,protein may be valid dual assignments for a conflated
node. We need to discuss more what the desired behavior is here, and for
compatibiklity with frameworks like ML frameworks that assume a single
category
