### ISSUE TITLE
use xsd: datatypes for literals in OWL output

### ISSUE THREAD

**Issue by smrgeoinfo** [linkml/linkml#510]
Running 1.1.13, Windows 10, CLI, generating OWL, format ttl 
command:
gen-owl -o isamples0.3owl.ttl -f ttl iSamplesSchemaBasic0.3.yml
[yaml file](https://github.com/isamplesorg/metadata/blob/main/iSamplesSchemaBasic0.3.yml)

literal slot ranges like 
```
slots:
    accessConstraints:
        range: string

```
get implemented as object properties like 
```
isam:accessConstraints a owl:ObjectProperty, linkml:SlotDefinition ;
    rdfs:range isam:String ;
```

I would expect these to be DatatypeProperty
```
isam:accessConstraints rdf:type owl:DatatypeProperty ;
                       rdfs:range xsd:string .
```

**Comment by cmungall** [comment]
TL;DR

Add this to the command line

`--no-type-objects`

There are some more details here:

https://linkml.io/linkml/generators/owl.html

We are likely to change the defaults in the future since I think most people would prefer any slot with a type range to be a DatatypeProperty, this odd decision to model with an extra level of indirection is historic.

lmk if this fixes your issue

**Comment by smrgeoinfo** [comment]
@cmungall that seems to solve the problem. Thanks.  I think making datatype properties would make more sense as the default.
