### ISSUE TITLE
define a default value for a slot: instantiate this default value in instances of the class.

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#633]
@LarsVogt

equals_string is helpful, but only on validation.  Is there a way to specify a default value for a slot that is instantiated in all (some?) of the serializations of the model?

**Comment by cmungall** [comment]
I think there is a distinction here

1. default values
2. fixed values

With default values, it's always possible to override. With fixed values, there is no override. I think @LargsVogt' use case applies to 2.

An example of 2 might be auto-adding a fixed schema version number to all datasets.

There are a few different ways to constrain a slot to a single value:

 * equals_string
 * equals_expression
 * string_serialization
 * enums with single permissible values

Any constraint can possibly be treated as inference rule. This is quite nuanced and touches on a lot of differences between CWA and OWA, think how "range" is intererpreted in OWL vs a database. LinkML is a CW system, so in one sense constraints are constraints, you must satisfy these otherwise the object is invalid.

However, there can be any number of tools that perform inference of any kind on objects, including filling in missing values. We need to better define the kinds of profiles for these different tools, but the basic idea is that any upstream tool can make use of the schema to perform population of missing values. In fact there is not-yet production code in the linkml-runtime for doing exactly this (utils.inference_utils).

But the key is that the constraints are still constraints, and if you pass data with the constrained value not set to either the linkml validator or to any generated schema (rdf passed to SHACL, json to JSON-Schema, tables to SQL DDL) and you do not run an upstream inference task then the data will be in violation.

I would be open to extension that allow the schema designer to say "I want X to be interpreted as an open world constraint" but we would have to work through exactly how that might work.

**Comment by LarsVogt** [comment]
What about ifabsent - could this be used to specify a slot-specific default value?

**Comment by nlharris** [comment]
I think if someone could quickly answer @LarsVogt's question above we could close this issue

**Comment by cmungall** [comment]
Yes, `ifabsent` should be used
