### ISSUE TITLE
yaml_dumper.dumps should use 'allow_unicode=True' as default parameter

### ISSUE THREAD

**Issue by StroemPhi** [linkml/linkml#634]
Special characters in utf-8 encoded data file YAML are loaded correctly using `yaml.loader.loads()`, but not dumped correctly in utf-8 using `yaml_dumper.dumps`, unless I set `allow_unicode=True`, which I found out reading [pyyaml#609](https://github.com/yaml/pyyaml/issues/609).

**To Reproduce**
see `created_by` value in input and output

dataset_info.yaml input file:
```
source_uri: doi:10.14272/QXXCRBSWGPRILJ-UHFFFAOYSA-N/CHMO0000595
source: Chemotion Repository
licence_str: Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
licence_url: https://creativecommons.org/licenses/by-sa/4.0/
date_created: "2022-01-10"
created_by: "Simone Gräßle"
```
loading as expected when using  `yaml_loader.loads(source="NMRspec/jdx_files/dataset_info.yaml", target_class=Provenance`:
```
Provenance(source='Chemotion Repository', description=None, source_uri='doi:10.14272/QXXCRBSWGPRILJ-UHFFFAOYSA-N.1', date_created='2022-01-10T00:00:00', licence_str='Attribution-ShareAli
ke 4.0 International (CC BY-SA 4.0)', licence_url='https://creativecommons.org/licenses/by-sa/4.0/', created_by='Simone Gräßle')
```
However, the output of `yaml_dumper.dumps(dataset_info)` is:
```
source: Chemotion Repository                                               
source_uri: doi:10.14272/QXXCRBSWGPRILJ-UHFFFAOYSA-N.1                     
date_created: '2022-01-10T00:00:00'                                        
licence_str: Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)       
licence_url: https://creativecommons.org/licenses/by-sa/4.0/               
created_by: "Simone Gr\xE4\xDFle"   
```
similar problem when using `json_dumper.dumps(dataset_info)`:

```
{                                                                          
  "source": "Chemotion Repository",                                        
  "source_uri": "doi:10.14272/QXXCRBSWGPRILJ-UHFFFAOYSA-N.1",              
  "date_created": "2022-01-10T00:00:00",                                   
  "licence_str": "Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
  "licence_url": "https://creativecommons.org/licenses/by-sa/4.0/",        
  "created_by": "Simone Gr\u00e4\u00dfle",                                 
  "@type": "Provenance"                                                    
}       
```                    

**Expected behavior**
Not having to set `allow_unicode=True` in `yaml_dumper.dumps(dataset_info, allow_unicode=True)`:
```                   
source: Chemotion Repository
source_uri: doi:10.14272/QXXCRBSWGPRILJ-UHFFFAOYSA-N.1
date_created: '2022-01-10T00:00:00'
licence_str: Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
licence_url: https://creativecommons.org/licenses/by-sa/4.0/
created_by: Simone Gräßle
```
 For the JSON dumper some other parameter must be set, which I didn't have the time to look for.

I guess, this should either be documented explicitly or changed to be the default in the [linkml-runtime dumper classes](https://github.com/linkml/linkml-runtime/tree/main/linkml_runtime/dumpers), as I would expect the output to be exactly the same as the input.

**Comment by dalito** [comment]
On which OS do you work?

**Comment by StroemPhi** [comment]
@dalito Win 10, Python 3.10.2 sorry that I forgot

**Comment by dalito** [comment]
My PR #607 addressed all parts exercised by the test suite. Maybe there are even more places which need fixing for windows.

**Comment by cmungall** [comment]
Thanks both!

Recall that there are two kinds of 'export' in linkml

1. [generators](https://linkml.io/linkml/generators/index.html) in the linkml package, which convert a schema
2. [dumpers](https://linkml.io/linkml/data/python.html) in the linkml_runtime package, which perform a direct translation of an object to rdf/json/ttl

#607 addresses 1, we need an equivalent for 2, would be awesome if one of you wants to handle it but no worries if you don't have time, I can have someone do this next week

**Comment by sujaypatil96** [comment]
Thank you for the analysis @StroemPhi and @dalito, it's much appreciated.

This issue best belongs in the linkml-runtime repo, since it's an issue related to one of the linkml-runtime methods, specifically, `YAMLDumper.dumps()` which you correctly identified in your analysis. Feel free to transfer the issue to the repo. If you can't, let us know and one the linkml maintainers can help you with it.

You've correctly identified that the dumper isn't able to recognize characters such as `äß` is because the `allow_unicode` attribute is set to `False` by default. And changing it `allow_unicode=True` successfully reads in those characters.

Could you help us by creating a test for this issue? There is a [CONTRIBUTING.md](https://github.com/linkml/linkml-runtime/blob/main/CONTRIBUTING.md) on the linkml-runtime repo, and there are instructions on how you can create a test case for this issue.

You can resuse the very same linkml schema you used for demo in the above example, load it in using the YAML loader and dump it using the YAML dumper. Create expected and actual result objects for the test and assert their equality accordingly.

Along with the test case, on the very same branch could you issue a fix in the [yaml_dumper.py](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/dumpers/yaml_dumper.py#L15-L16) file, by adding a `allow_unicode=True` argument to L16.

**Comment by sujaypatil96** [comment]
Thank you @dalito. My apologies, I missed your PR on the linkml-runtime repo.

I've left a review on your PR.🚀
