### ISSUE TITLE
implement tutorial feedback

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#636]
Some feedback @matentzn and I got

- we ask some tutorial questions e.g in https://linkml.io/linkml/intro/tutorial01.html but don't provide answers
- add similar questions (and answers) for part 4-8

@matentzn I can implement this but wanted your feedback first on overall alignment with OBO tutorials - e.g. do we usually give answers in the same doc, in a gist, ...?

**Comment by matentzn** [comment]
@matentzn the LinkML tutorials are beautiful. We do not have any "tutorial" questions at all in obo-academy at the moment - everything is walkthrough and self-contained, like: do this, then this, then run this, observe this, etc.. We are discussing in the context of a certification mechanism how testing should at all be realised in a way that does not put a too strong burden on us (ideally none). 

I think just for sanity's sake, for now, I would keep tutorials without any open questions: if the questions that are currently there extend a previously introduced idea, then we should provide a walk through to the answer the same way as the rest of the tutorial. Otherwise do not bother (this is not because I think its bad to include such questions, just avoid extra work with model answers curated elsewhere that need to be kept in sync, etc etc).

**Comment by cmungall** [comment]
lightweight approach: we can make issues of the form "how do I do X" where that is the question in the tutorial. We can link the issue to the tutorial docs. added bonus is people searching issues for how to do X will find the answer

**Comment by cmungall** [comment]
OK, I think we will adopt the approach of simply leaving no unopened questions as Nico suggests
