### ISSUE TITLE
schemaloader complains if ifabsent value is an integer expression

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#675]
the metamodel has:

```yaml
  ifabsent:
    domain: slot_definition
    range: string
    inherited: true
    description:  |-
      function that provides a default value for the slot.  Possible values for this slot are defined in
      linkml_runtime.utils.ifabsent_functions.default_library:
        * [Tt]rue -- boolean True
        * [Ff]alse -- boolean False
        * int(value) -- integer value
        * str(value) -- string value
        * default_range -- schema default range
        * bnode -- blank node identifier
        * slot_uri -- URI for the slot
        * class_curie -- CURIE for the containing class
        * class_uri -- URI for the containing class
    close_mappings:
      - sh:defaultValue
```

however using `int(0)` results in 

  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/data-manifesto-OWid1XU8-py3.9/lib/python3.9/site-packages/linkml/utils/schemaloader.py", line 788, in raise_value_errors
    raise ValueError(f'{TypedNode.yaml_loc(loc_str, suffix="")} {error}')
ValueError: File "<file>", line 190, col 19 Unrecognized ifabsent action for slot 'contentCheck__minimum_line_number': 'int(0)'

**Comment by hsolbrig** [comment]
Fixed in https://github.com/linkml/linkml/pull/1171. 

Note, however, that we really should take a look at the `ifabsent` attribute to see whether we've got stuff in there that isn't needed and/or are missing stuff.  In particular, I wonder whether we should deprecate `string` and `int` and, instead,  accept `"string value"` for string and any json / yaml parsable type (e.g.  `17` for int, `17.2` for float, etc.

**Comment by cmungall** [comment]
> In particular, I wonder whether we should deprecate string and int and, instead, accept "string value" for string and any json / yaml parsable type (e.g. 17 for int, 17.2 for float, etc.

Agreed. This is how it works with `equals_expression`

**Comment by sierra-moxon** [comment]
closed as complete.
