### ISSUE TITLE
Discussion: rule language for data model transforms

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#75]
I don't know whether this belongs in blml or outside.

There are various cases where we want to specify transforms - between two schemas; or within a schema for derived values, non-transitive inference

E.g

 * `schema1.person.name = schema2.person.firstname + ' ' schema2.person.lastname`
 * `all person x, person y: x.father_of = y -> y.has_father = x`
 * normalization/denormalization:
    * `transaction.person_firstname = x, transaction.person_lastname = y <-> transaction.person = {firstname: x, lastname: y}`

The same language could be done with constraints

There are various ways this could be done

 - our own language
 - shacl rules (is there a shex analog @hsolbrig ?)
 - procedural code
 - any of the various rule frameworks associated with Protege3/frames
 - UML based solution e.g. OCL
 - Something like Flora2
 - Prolog
 - CommonLogic
 - Koza
 - SSSOM (but not really applicable for complex rules)
 - ...

This seems overkill for core blml. However, we do have limited expressivity constraints already, e.g. min and max values. Our string_serialization method is in some sense this. It might be useful for building some limited expressivity constructs into the metamodel, e.g. just for the norm/denorm use case.

**Comment by ddooley** [comment]
DataHarmonizer has an example use case: Where a submitting agency is providing a specimen rather than any sequencing results to a repository (&testing lab), set metadata of all empty sequencing section fields to "Not Applicable". 

For a given data entry template class, if ‘NML submitted specimen type’ slot value is not a null value, then for any sequencing section slot value, if empty, enter 'Not Applicable'.  I was wondering how this might be expressed in LinkML directly? 

Paraphrasing what I gather is emerging LinkML rule syntax (but is there a document outlining this)?  [field] is a kind of wildcard variable that seems to be needed.

rules:
    - preconditions:
        - slot_conditions:
            - NML submitted specimen type
                 - any_of:
                      -  NML submitted specimen type **menu** (an enumeration)
            - sequencing.[field]
                    - any_of:
                           - blank
     - postconditions:
         - slot_conditions:
             - [field]:    
                 - pattern: "Not Applicable"
