### ISSUE TITLE
Do enums allow nested permissible_values? SchemaView() triggering error on that structure.

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#752]
**Describe the bug**
It seems like enums that have nested permissible_values are throwing a parsing error in SchemaView()

Or am I just not getting the structure right? I assumed nested permissible_values were allowed so enumerations could show hierarchy.  Are they only allowed to be flat?

I have a "signs and symptoms menu" (yaml view) with the following permissible_values tree::
```

enums:
...

  signs and symptoms menu:
    name: signs and symptoms menu
    permissible_values:
      Abnormal lung auscultation:
        text: Abnormal lung auscultation
        meaning: HP:0030829
      Abnormality of taste sensation:
        text: Abnormality of taste sensation
        meaning: HP:0000223
        permissible_values:
          Ageusia (complete loss of taste):
            text: Ageusia (complete loss of taste)
            meaning: HP:0041051
          Parageusia (distorted sense of taste):
            text: Parageusia (distorted sense of taste)
            meaning: HP:0031249
          Hypogeusia (reduced sense of taste):
            text: Hypogeusia (reduced sense of taste)
            meaning: HP:0000224
      Abnormality of the sense of smell:
        text: Abnormality of the sense of smell
        meaning: HP:0004408
        permissible_values:
          Anosmia (lost sense of smell):
            text: Anosmia (lost sense of smell)
            meaning: HP:0000458
```

It is generating an error when being parsed by SchemaView().

`ValueError:  Unknown argument: permissible_values = {'Ageusia (complete loss of taste)': {'t`

**To Reproduce**
1. Check out https://github.com/cidgoh/DataHarmonizer/tree/WIP-validation
2. in root folder "make canada_covid19"

**Expected behavior**
Error shouldn't be thrown?

**Screenshots**
![image](https://user-images.githubusercontent.com/4000582/167078622-9af7ce9c-1794-4f8f-8f90-ef9dc3402b94.png)
...
![image](https://user-images.githubusercontent.com/4000582/167078072-5d142576-80d0-48c9-ace2-fd0ae29380c0.png)

**Comment by ddooley** [comment]
Ok, reading the spec again, it seems permissible_values is a flat list. but that elements of that list can establish a hierarchy by making is_a references to each other?

**Comment by turbomam** [comment]
I can look in about an hour

**Comment by turbomam** [comment]
I'm trying to get up to speed. This comment probably doesn't have anything to do with your underlying enum/PV/is_a issue

You have these

- ./schema.yaml
- ./schema_core.yaml

In  `template/canada_covid19` but it doesn't look like either imports the other. Do I need to understand the differences between the two schema files?

**Comment by turbomam** [comment]
I'm getting 

> ValueError:  Unknown argument: permissible_values = {'Ageusia (complete loss of taste)': {'t

from 

```shell
make canada_covid19
```

**Comment by ddooley** [comment]
Right, that error was the first one I ran into.  I'll now upload the revised schema.yaml so you can see the subsequent error after getting rid of permissible_values recursion.

And yes just using schema.yaml.  The schema_core.yaml is combined with the tabular stuff in a conversion script to yield schema.yaml

**Comment by turbomam** [comment]
I see lots of other LinkML violations in here, besides enums/PV violations. I'll have a report on that soon.

**Comment by ddooley** [comment]
Oh, argh! I just uploaded a crap schema.yaml  .  Was trying to fix another problem.  Will revise in a sec and send that up, it has no errors except the one exact_mappings one.

**Comment by turbomam** [comment]
you should be able to run `gen-yaml` on the LinkML file and get YAML output to STDOUT (no errors) before you even try to make the DH JSON

**Comment by ddooley** [comment]
new version uploaded to WIP-validation

**Comment by turbomam** [comment]
OK, I'm getting the same error as you now

> Unknown argument: exact_mappings = ['CNPHI:ARDS']

Unfortunately, while the current LinkML meta model does say that permissible_values can have mappings, the LinkML runtime is using a LinkML meta model that's one version behind. @cmungall and I worked on that now and the synchronized LinkML runtime should be out early next week.

**Comment by turbomam** [comment]
I also see that you are using `xs:` CURIEs as the ranges for some of your slots. I don't think that will pass LinkML schema validation without defining the `xs:` prefix and either defining the datatypes themselves, or at least mapping the `xs:` datatypes to existing LinkML datatypes.

We should Zoom soon. I like the way you're tying things together here. I could have done a better job of explaining LinkML types to you. Maybe some other constructs, too.

**Comment by ddooley** [comment]
Ok, thanks for clarifying.  I can wait!

Ah yes, xs: needs to be converted to xsd, will do!

**Comment by turbomam** [comment]
BTW, is `xs:unique` really a datatype? I don't see it in https://www.w3.org/TR/xmlschema-2/

It is mentioned [here](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256142(v=vs.100)), but as an identity constraint.

**Comment by ddooley** [comment]
Ah, that is supposed to be converted to identifier = True in linkml schema.  I did that part, but forgot to then convert xs:unique into xsd:token

**Comment by turbomam** [comment]
Let me know what I can do to help.

**Comment by ddooley** [comment]
Just get that exact_mappings property working in main linkml code and I'll be happy.  Ideally a decision too on whether minimum_value and maximum_value [allowing dates](https://github.com/linkml/linkml/issues/751) or even {today} magic are agreeable would be great.

**Comment by turbomam** [comment]
name | base | description | repr | uri | notes | comments
-- | -- | -- | -- | -- | -- | --
boolean | Bool | A binary (true or false) value | bool | xsd:boolean |   |  
date | XSDDate | a date (year, month and day) in an idealized calendar | str | xsd:date | URI is dateTime because OWL reasoners don't work with straight date or   time |  
datetime | XSDDateTime | The combination of a date and time | str | xsd:dateTime |   |  
decimal | Decimal | A real number with arbitrary precision that conforms to the xsd:decimal   specification |   | xsd:decimal |   |  
double | float | A real number that conforms to the xsd:double specification |   | xsd:double |   |  
float | float | A real number that conforms to the xsd:float specification |   | xsd:float |   |  
integer | int | An integer |   | xsd:integer |   |  
ncname | NCName | Prefix part of CURIE | str | xsd:string |   |  
nodeidentifier | NodeIdentifier | A URI, CURIE or BNODE that represents a node in a model. | str | shex:nonLiteral |   |  
objectidentifier | ElementIdentifier | A URI or CURIE that represents an object in the model. | str | shex:iri |   | Used for inheritence and type checking
string | str | A character string |   | xsd:string |   |  
time | XSDTime | A time object represents a (local) time of day, independent of any   particular day | str | xsd:dateTime | URI is dateTime because OWL reasoners don't work with straight date or   time |  
uri | URI | a complete URI | str | xsd:anyURI |   |  
uriorcurie | URIorCURIE | a URI or a CURIE | str | xsd:anyURI |   |

**Comment by ddooley** [comment]
One other thing is to see if the HandsOnTable work to have dependent single and multiselect enumerations can be powered by an enumeration list in which items have a "pertinent to" link to (possibly hierarchical) choices of other enums.  I really think this dependancy info should be coded directly in the enums field.
