### ISSUE TITLE
add issue template to linkml-runtime encouraging submission of issues to main linkml repo

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#810]

**Comment by nlharris** [comment]
I was going to work on this, but I'm not sure what the template should be called ("Are you sure you want to submit your issue here?"?) and what, if any, alternate templates should be offered ("Yes, I'm sure!"?).

@sujaypatil96 I assume you've created issue templates before, but if you haven't, I'm happy to help.

**Comment by dalito** [comment]
Maybe add just a message or use a sticky issue at the top, like e.g. [mypy](https://github.com/python/mypy/issues) has?

**Comment by nlharris** [comment]
Did the "sticky issue" thing as well as changing the instructions
https://github.com/linkml/linkml-runtime/issues
