### ISSUE TITLE
gen-docs pages about enumerations should show the slots that use the enum

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#998]
this is another case of showing inbound relationships

**Comment by sujaypatil96** [comment]
@amc-corey-cox do you want to take this on? It's a nice issue, I can expand on the requirements.

**Comment by sujaypatil96** [comment]
Consider the NMDC schema as an example schema that is generated using gen-doc. Find the NMDC schema documentation here: https://microbiomedata.github.io/nmdc-schema/. Within this schema, you can find the [Biosample](https://microbiomedata.github.io/nmdc-schema/Biosample/) class and links to slots that are associated with the class in a [slots](https://microbiomedata.github.io/nmdc-schema/Biosample/#slots) table. That is what @turbomam classifies as an _outbound_ relationship. When you click on a slot page through that table, you can see an _Applicable Classes_ table on a slot page and can link back to a class page from that table, and that is what @turbomam classifies as an _inbound_ relationship. The acceptance criteria for the completion of this issue is to implement the same strategy for slot and enum pages. For example be able to get to page [biotic_relationship](https://microbiomedata.github.io/nmdc-schema/biotic_relationship/) from [BioticRelationshipEnum](https://microbiomedata.github.io/nmdc-schema/BioticRelationshipEnum/) page.
